# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-23 09:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import internationalflavor.vat_number.models
import localflavor.us.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=20)),
                ('start', models.DateField()),
                ('end', models.DateField(blank=True, null=True)),
                ('comment', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('account_ID', models.CharField(max_length=16, primary_key=True, serialize=False, unique=True)),
                ('full_Name', models.CharField(blank=True, max_length=96)),
                ('acronym', models.CharField(blank=True, max_length=32)),
                ('website', models.URLField(blank=True)),
                ('address', models.CharField(max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=16)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('state', models.CharField(blank=True, max_length=30)),
                ('us_state', localflavor.us.models.USStateField(blank=True)),
                ('VAT', internationalflavor.vat_number.models.VATNumberField(blank=True)),
                ('date_added', models.DateField()),
                ('customer_type', models.CharField(choices=[('Gov', 'Government'), ('Edu', 'Education'), ('Co', 'Corporation'), ('Ind', 'Individual'), ('Pri', 'Private')], max_length=3)),
                ('status', models.CharField(choices=[('V', 'Valid'), ('I', 'Invalid')], max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('telephone', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='silson.Staff'),
        ),
        migrations.AddField(
            model_name='customer',
            name='associate',
            field=models.ManyToManyField(through='silson.Affiliation', to='silson.User'),
        ),
        migrations.AddField(
            model_name='affiliation',
            name='associate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silson.Customer'),
        ),
        migrations.AddField(
            model_name='affiliation',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silson.User'),
        ),
    ]
