# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-23 09:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('silson', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='affiliation',
            old_name='comment',
            new_name='comments',
        ),
    ]
