# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-12 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silson', '0003_historicalaffiliation_historicalcustomer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='staff',
            name='telephone',
            field=models.CharField(blank=True, max_length=14),
        ),
    ]
