# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-13 11:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('silson', '0004_auto_20160912_0752'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_No', models.CharField(max_length=10)),
                ('p_order_no', models.CharField(max_length=10)),
                ('p_order_date', models.DateField(blank=True)),
                ('po_acknowledged', models.DateField(blank=True)),
                ('ship_by', models.CharField(choices=[('FedEx', 'FedEx'), ('DHL', 'DHL'), ('DPD', 'DPD')], max_length=7)),
                ('end_user', models.CharField(max_length=12)),
                ('date_received', models.DateField(blank=True)),
                ('disp_date', models.DateField(blank=True)),
                ('disp_advised', models.DateField(blank=True)),
                ('POD_Date', models.DateField(blank=True)),
                ('invoice_No', models.CharField(blank=True, max_length=10)),
                ('invoice_Date', models.DateField(blank=True)),
                ('payment_received', models.DateField(blank=True)),
                ('comments', models.TextField(default='POST INVOICE')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silson.Customer')),
                ('purchase_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silson.User')),
            ],
        ),
        migrations.CreateModel(
            name='Mask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=12)),
                ('membrane_size', models.CharField(max_length=10)),
                ('wafer_dia', models.IntegerField(default=0)),
                ('wafer_thickness', models.IntegerField(default=0)),
                ('number_available', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Process_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_No', models.CharField(max_length=10)),
                ('job_Date', models.DateField()),
                ('number_required', models.IntegerField(default=0)),
                ('membrane_thickness', models.IntegerField(default=0)),
                ('frame_size', models.FloatField(default=0)),
                ('frame_added_to_stock', models.IntegerField(default=0)),
                ('apertures', models.TextField(blank=True)),
                ('comment', models.TextField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silson.Customer')),
                ('job_No', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Jobb')),
                ('mask_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Mask')),
            ],
        ),
        migrations.CreateModel(
            name='Wafer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=15)),
                ('coating', models.CharField(max_length=12)),
                ('coating_thickness', models.IntegerField(default=0)),
                ('diameter', models.FloatField(default=0)),
                ('silicon_date', models.DateField()),
                ('box_no', models.IntegerField(default=0)),
                ('no_of_wafers', models.IntegerField(default=0)),
                ('stress', models.CharField(max_length=5)),
                ('polish', models.CharField(max_length=8)),
                ('wafer_thickness', models.IntegerField(default=0)),
                ('membrane_thickness', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='process_record',
            name='wafer_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Wafer'),
        ),
    ]
