# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-15 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mask',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mask',
            name='frame_size',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='wafer',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='jobb',
            name='comments',
            field=models.TextField(default=True),
        ),
        migrations.AlterField(
            model_name='mask',
            name='membrane_size',
            field=models.FloatField(max_length=10),
        ),
    ]
