# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-15 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20160915_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobb',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
